services:
  - type: web
    name: neic-backend
    runtime: python
    region: singapore
    buildCommand: pip install -r app/backend/requirements.txt
    startCommand: uvicorn app.backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT
        value: serviceAccountKey.json
      - key: ALLOWED_ORIGINS
        sync: false
      - key: DATABASE_URL
        value: sqlite:///./election_chatbot.db
      - key: PYTHON_VERSION
        value: "3.12"
